language: julia

os:
  - linux

julia:
  - nightly

before_script:
  - julia -e 'using Pkg; Pkg.add("Conda"); using Conda; Conda.add("matplotlib"); Conda.add("cartopy")';

matrix:
  allow_failures:
  - julia: nightly

notifications:
  email: false


